apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
  labels:
    app: broker
spec:
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: localhost:32000/dataflowx:v1
        imagePullPolicy: Always
        command: ["python"]
        args: ["broker.py"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: localhost:32000/dataflowx:v1
        imagePullPolicy: Always
        command: ["python3"]
        args: ["worker.py"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        imagePullPolicy: Always
        image: localhost:32000/dataflowx:v1
        command: ["python3"]
        args: ["test.py"]
