version: "2"
services:
  web:
    platform: linux/amd64
    build: .
    expose:
      - "9080"
    #ports:
    #  - "9080:9080"
    command: ["python3.7", "test.py"]
    deploy:
      mode: replicated
      replicas: 5
    restart: always
    links:
      - broker
  broker:
    platform: linux/amd64
    build: .
    command: ["python3.7", "/usr/src/myapp/broker.py"]
  worker:
    platform: linux/amd64
    build: .
    command: ["python3.7", "/usr/src/myapp/worker.py"]
    deploy:
      mode: replicated
      replicas: 3
    links:
      - broker
